START TRANSACTION;
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AD','Andorra');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AE','Emirati Arabi Uniti');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AF','Afghanistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AG','Antigua e Barbuda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AI','Anguilla');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AL','Albania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AM','Armenia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AO','Angola');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AQ','Antartide');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AR','Argentina');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AS','Samoa Americane');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AT','Austria');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AU','Australia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AW','Aruba');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AX','Isole Åland');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('AZ','Azerbaigian');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BA','Bosnia ed Erzegovina');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BB','Barbados');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BD','Bangladesh');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BE','Belgio');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BF','Burkina Faso');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BG','Bulgaria');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BH','Bahrain');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BI','Burundi');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BJ','Benin');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BL','Saint-Barthélemy');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BM','Bermuda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BN','Brunei');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BO','Bolivia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BQ','Isole BES');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BR','Brasile');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BS','Bahamas');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BT','Bhutan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BV','Isola Bouvet');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BW','Botswana');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BY','Bielorussia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('BZ','Belize');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CA','Canada');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CC','Isole Cocos e Keeling');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CD','Repubblica Democratica del Congo');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CF','Repubblica Centrafricana');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CG','Repubblica del Congo');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CH','Svizzera');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CI','Costa d Avorio');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CK','Isole Cook');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CL','Cile');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CM','Camerun');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CN','Cina');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CO','Colombia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CR','Costa Rica');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CU','Cuba');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CV','Capo Verde');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CW','Curaçao');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CX','Isola del Natale');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CY','Cipro');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('CZ','Repubblica Ceca');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('DE','Germania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('DJ','Gibuti');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('DK','Danimarca');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('DM','Dominica');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('DO','Repubblica Dominicana');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('DZ','Algeria');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('EC','Ecuador');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('EE','Estonia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('EG','Egitto');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('EH','Sahara Occidentale');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ER','Eritrea');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ES','Spagna');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ET','Etiopia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('FI','Finlandia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('FJ','Figi');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('FK','Isole Falkland');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('FM','Stati Federati di Micronesia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('FO','Isole Fær Øer');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('FR','Francia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GA','Gabon');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GB','Regno Unito');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GD','Grenada');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GE','Georgia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GF','Guyana Francese');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GG','Guernsey');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GH','Ghana');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GI','Gibilterra');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GL','Groenlandia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GM','Gambia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GN','Guinea');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GP','Guadalupa');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GQ','Guinea Equatoriale');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GR','Grecia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GS','Georgia del Sud e isole Sandwich meridionali');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GT','Guatemala');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GU','Guam');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GW','Guinea-Bissau');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('GY','Guyana');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('HK','Hong Kong');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('HM','Isole Heard e McDonald');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('HN','Honduras');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('HR','Croazia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('HT','Haiti');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('HU','Ungheria');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ID','Indonesia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IE','Irlanda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IL','Israele');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IM','Isola di Man');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IN','India');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IO','Territori Britannici dell Oceano Indiano');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IQ','Iraq');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IR','Iran');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IS','Islanda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('IT','Italia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('JE','Jersey');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('JM','Giamaica');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('JO','Giordania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('JP','Giappone');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KE','Kenya');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KG','Kirghizistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KH','Cambogia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KI','Kiribati');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KM','Comore');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KN','Saint Kitts e Nevis');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KP','Corea del Nord');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KR','Corea del Sud');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KW','Kuwait');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KY','Isole Cayman');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('KZ','Kazakistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LA','Laos');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LB','Libano');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LC','Santa Lucia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LI','Liechtenstein');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LK','Sri Lanka');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LR','Liberia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LS','Lesotho');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LT','Lituania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LU','Lussemburgo');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LV','Lettonia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('LY','Libia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MA','Marocco');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MC','Monaco');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MD','Moldavia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ME','Montenegro');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MF','Saint-Martin');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MG','Madagascar');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MH','Isole Marshall');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MK','Macedonia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ML','Mali');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MM','Birmania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MN','Mongolia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MO','Macao');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MP','Isole Marianne Settentrionali');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MQ','Martinica');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MR','Mauritania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MS','Montserrat');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MT','Malta');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MU','Mauritius');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MV','Maldive');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MW','Malawi');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MX','Messico');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MY','Malesia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('MZ','Mozambico');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NA','Namibia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NC','Nuova Caledonia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NE','Niger');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NF','Isola Norfolk');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NG','Nigeria');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NI','Nicaragua');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NL','Paesi Bassi');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NO','Norvegia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NP','Nepal');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NR','Nauru');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NU','Niue');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('NZ','Nuova Zelanda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('OM','Oman');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PA','Panamá');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PE','Perù');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PF','Polinesia Francese');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PG','Papua Nuova Guinea');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PH','Filippine');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PK','Pakistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PL','Polonia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PM','Saint Pierre e Miquelon');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PN','Isole Pitcairn');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PR','Porto Rico');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PS','Stato di Palestina');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PT','Portogallo');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PW','Palau');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('PY','Paraguay');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('QA','Qatar');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('RE','Réunion');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('RO','Romania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('RU','Russia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('RS','Serbia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('RW','Ruanda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SA','Arabia Saudita');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SB','Isole Salomone');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SC','Seychelles');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SD','Sudan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SE','Svezia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SG','Singapore');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SH','Sant Elena, Isola di Ascensione e Tristan da Cunha');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SI','Slovenia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SJ','Svalbard e Jan Mayen');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SK','Slovacchia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SL','Sierra Leone');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SM','San Marino');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SN','Senegal');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SO','Somalia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SR','Suriname');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SS','Sudan del Sud');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ST','São Tomé e Príncipe');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SV','El Salvador');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SX','Sint Maarten');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SY','Siria');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('SZ','Swaziland');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TC','Isole Turks e Caicos');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TD','Ciad');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TF','Territori Francesi del Sud');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TG','Togo');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TH','Thailandia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TJ','Tagikistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TK','Tokelau');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TL','Timor Est');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TM','Turkmenistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TN','Tunisia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TO','Tonga');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TR','Turchia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TT','Trinidad e Tobago');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TV','Tuvalu');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TW','Repubblica di Cina');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('TZ','Tanzania');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('UA','Ucraina');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('UG','Uganda');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('UM','Isole minori esterne degli Stati Uniti');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('US','Stati Uniti d America');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('UY','Uruguay');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('UZ','Uzbekistan');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VA','Città del Vaticano');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VC','Saint Vincent e Grenadine');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VE','Venezuela');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VG','Isole Vergini Britanniche');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VI','Isole Vergini Americane');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VN','Vietnam');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('VU','Vanuatu');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('WF','Wallis e Futuna');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('WS','Samoa');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('YE','Yemen');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('YT','Mayotte');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ZA','Sudafrica');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ZM','Zambia');
insert into  pariopp.nazioni (ID,DESCRIZIONE) values('ZW','Zimbabwe');
COMMIT;
