START TRANSACTION;
insert into  pariopp.lingue (ID,DESCRIZIONE) values('afh','Afrihili');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('afr','Afrikaans');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('afa','Afro-Asiatic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ain','Ainu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('aka','Akan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('akk','Akkadian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('alb','Albanian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sqi','Albanian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ale','Aleut');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('alg','Algonquian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tut','Altaic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('amh','Amharic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('anp','Angika');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('apa','Apache languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ara','Arabic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('arg','Aragonese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('arp','Arapaho');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('arw','Arawak');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('arm','Armenian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hye','Armenian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('rup','Aromanian; Arumanian; Macedo-Romanian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('art','Artificial languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('asm','Assamese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ast','Asturian; Asturleonese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ath','Athapascan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('aus','Australian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('map','Austronesian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ava','Avaric');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ave','Avestan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('awa','Awadhi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('aym','Aymara');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('aze','Azerbaijani');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ban','Balinese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bat','Baltic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bal','Baluchi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bam','Bambara');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bai','Bamileke languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bad','Banda languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bnt','Bantu languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bas','Basa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bak','Bashkir');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('baq','Basque');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('btk','Batak languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bej','Bedawiyet');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bel','Belarusian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bem','Bemba');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ben','Bengali');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ber','Berber languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bho','Bhojpuri');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bih','Bihari languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bik','Bikol');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bin','Bini');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bis','Bislama');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('byn','Blin');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zbl','Bliss');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nob','Bokmål, Norwegian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bos','Bosnian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bra','Braj');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bre','Breton');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bug','Buginese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bul','Bulgarian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bua','Buriat');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('bur','Burmese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mya','Burmese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cad','Caddo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('spa','Castilian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cat','Catalan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cau','Caucasian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ceb','Cebuano');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cel','Celtic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cai','Central American Indian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('khm','Central Khmer');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chg','Chagatai');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cmc','Chamic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cha','Chamorro');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('che','Chechen');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chr','Cherokee');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chy','Cheyenne');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chb','Chibcha');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chi','Chinese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zho','Chinese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chn','Chinook jargon');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chp','Chipewyan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cho','Choctaw');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zha','Chuang');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chu','Church Slavic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chk','Chuukese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chv','Chuvash');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nwc','Classical Nepal Bhasa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('syc','Classical Syriac');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('rar','Cook Islands Maori');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cop','Coptic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cor','Cornish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cos','Corsican');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cre','Cree');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mus','Creek');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('crp','Creoles and pidgins');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cpe','Creoles and pidgins, English based');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cpf','Creoles and pidgins, French-based');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cpp','Creoles and pidgins, Portuguese-based');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('crh','Crimean Tatar');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hrv','Croatian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cus','Cushitic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cze','Czech');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ces','Czech');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dak','Dakota');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dan','Danish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dar','Dargwa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('del','Delaware');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('div','Dhivehi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zza','Dimili');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('din','Dinka');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('doi','Dogri');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dgr','Dogrib');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dra','Dravidian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dua','Duala');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dut','Dutch');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nld','Dutch');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dum','Dutch, Middle (ca.1050-1350)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dyu','Dyula');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dzo','Dzongkha');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('frs','Eastern Frisian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('efi','Efik');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('egy','Egyptian (Ancient)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('eka','Ekajuk');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('elx','Elamite');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('eng','English');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('enm','English, Middle (1100-1500)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ang','English, Old (ca.450-1100)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('myv','Erzya');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('epo','Esperanto');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('est','Estonian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ewe','Ewe');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ewo','Ewondo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fan','Fang');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fat','Fanti');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fao','Faroese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fij','Fijian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fil','Filipino');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fin','Finnish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fiu','Fi-Ugrian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fon','Fon');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fre','French');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fra','French');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('frm','French, Middle (ca.1400-1600)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fro','French, Old (842-ca.1400)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fur','Friulian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ful','Fulah');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gaa','Ga');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gla','Gaelic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('car','Galibi Carib');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('glg','Galician');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lug','Ganda');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gay','Gayo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gba','Gbaya');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gez','Geez');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('geo','Georgian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kat','Georgian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ger','German');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('deu','German');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nds','German, Low');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gmh','German, Middle High (ca.1050-1500)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('goh','German, Old High (ca.750-1050)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gem','Germanic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kik','Gikuyu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gil','Gilbertese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gon','Gondi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gor','Gorontalo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('got','Gothic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('grb','Grebo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('grc','Greek, Ancient (to 1453)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gre','Greek, Modern (1453-)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ell','Greek, Modern (1453-)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kal','Greenlandic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('grn','Guarani');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('guj','Gujarati');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gwi','Gwich in');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hai','Haida');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hat','Haitian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hau','Hausa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('haw','Hawaiian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('heb','Hebrew');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('her','Herero');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hil','Hiligaynon');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('him','Himachali languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hin','Hindi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hmo','Hiri Motu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hit','Hittite');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hmn','Hmong');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hun','Hungarian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hup','Hupa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('iba','Iban');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ice','Icelandic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('isl','Icelandic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ido','Ido');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ibo','Igbo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ijo','Ijo languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ilo','Iloko');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('arc','Imperial Aramaic (700-300 BCE)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('smn','Inari Sami');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('inc','Indic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ine','Indo-European languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ind','Indonesian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('inh','Ingush');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ina','Interlingua (International Auxiliary Language Association)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('iku','Inuktitut');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ipk','Inupiaq');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ira','Iranian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gle','Irish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mga','Irish, Middle (900-1200)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sga','Irish, Old (to 900)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('iro','Iroquoian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ita','Italian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('jpn','Japanese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('jav','Javanese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('jrb','Judeo-Arabic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('jpr','Judeo-Persian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kbd','Kabardian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kab','Kabyle');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kac','Kachin');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('xal','Kalmyk');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kam','Kamba');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kan','Kannada');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kau','Kanuri');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pam','Kapampangan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kaa','Kara-Kalpak');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('krc','Karachay-Balkar');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('krl','Karelian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kar','Karen languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kas','Kashmiri');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('csb','Kashubian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kaw','Kawi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kaz','Kazakh');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kha','Khasi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('khi','Khoisan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kho','Khotanese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kmb','Kimbundu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kin','Kinyarwanda');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tlh','Klingon');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kom','Komi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kon','Kongo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kok','Konkani');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kor','Korean');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kos','Kosraean');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kpe','Kpelle');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kro','Kru languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kum','Kumyk');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kur','Kurdish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kru','Kurukh');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kut','Kutenai');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kua','Kwanyama');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('kir','Kyrgyz');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lad','Ladino');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lah','Lahnda');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lam','Lamba');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('day','Land Dayak languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lao','Lao');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lat','Latin');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lav','Latvian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ltz','Letzeburgesch');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lez','Lezghian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lim','Limburgan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lin','Lingala');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lit','Lithuanian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('jbo','Lojban');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('dsb','Lower Sorbian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('loz','Lozi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lub','Luba-Katanga');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lua','Luba-Lulua');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lui','Luiseno');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('smj','Lule Sami');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lun','Lunda');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('luo','Luo (Kenya and Tanzania)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lus','Lushai');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mac','Macedonian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mkd','Macedonian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mad','Madurese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mag','Magahi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mai','Maithili');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mak','Makasar');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mlg','Malagasy');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('may','Malay');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('msa','Malay');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mal','Malayalam');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mlt','Maltese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mnc','Manchu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mdr','Mandar');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('man','Mandingo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mni','Manipuri');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mno','Manobo languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('glv','Manx');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mao','Maori');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mri','Maori');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('arn','Mapuche');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mar','Marathi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('chm','Mari');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mah','Marshallese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mwr','Marwari');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mas','Masai');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('myn','Mayan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('men','Mende');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mic','Mi kmaq');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('min','Minangkabau');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mwl','Mirandese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('moh','Mohawk');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mdf','Moksha');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('rum','Moldavian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mkh','Mon-Khmer languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('lol','Mongo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mon','Mongolian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mos','Mossi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mul','Multiple languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mun','Munda languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nqo','NKo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nah','Nahuatl languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nau','Nauru');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nav','Navaho');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nde','Ndebele, North');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nbl','Ndebele, South');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ndo','Ndonga');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nap','Neapolitan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nep','Nepali');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('new','Newari');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nia','Nias');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nic','Niger-Kordofanian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ssa','Nilo-Saharan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('niu','Niuean');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zxx','No linguistic content');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nog','Nogai');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('non','Norse, Old');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nai','North American Indian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('frr','Northern Frisian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sme','Northern Sami');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nso','Northern Sotho');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nor','Norwegian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nub','Nubian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('iii','Nuosu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nym','Nyamwezi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nya','Nyanja');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nyn','Nyankole');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nno','Nynorsk, Norwegian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nyo','Nyoro');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('nzi','Nzima');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ile','Occidental');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('oci','Occitan (post 1500)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pro','Occitan, Old (to 1500)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('oji','Ojibwa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ori','Oriya');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('orm','Oromo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('osa','Osage');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('oss','Ossetian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('oto','Otomian languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pal','Pahlavi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pau','Palauan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pli','Pali');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pag','Pangasinan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pan','Panjabi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pap','Papiamento');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('paa','Papuan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pus','Pashto');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('per','Persian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fas','Persian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('peo','Persian, Old (ca.600-400 B.C.)');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('phi','Philippine languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('phn','Phoenician');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pon','Pohnpeian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pol','Polish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('por','Portuguese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('pra','Prakrit languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('que','Quechua');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('raj','Rajasthani');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('rap','Rapanui');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('qaa-qtz','Reserved for local use');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('roa','Romance languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ron','Romanian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('roh','Romansh');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('rom','Romany');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('run','Rundi');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('rus','Russian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sal','Salishan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sam','Samaritan Aramaic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('smi','Sami languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('smo','Samoan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sad','Sandawe');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sag','Sango');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('san','Sanskrit');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sat','Santali');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('srd','Sardinian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sas','Sasak');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sco','Scots');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sel','Selkup');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sem','Semitic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('srp','Serbian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('srr','Serer');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('shn','Shan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sna','Shona');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('scn','Sicilian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sla','Slavic languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('slo','Slovak');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('som','Somali');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('son','Songhai languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('srn','Sranan Tongo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('swa','Swahili');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ssw','Swati');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('swe','Swedish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('gsw','Swiss German; Alemannic; Alsatian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tah','Tahitian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tai','Tai languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tib','Tibetan');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tur','Turkish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('tuk','Turkmen');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ukr','Ukrainian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('umb','Umbundu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('mis','Uncoded languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('und','Undetermined');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('hsb','Upper Sorbian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('urd','Urdu');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('uig','Uyghur');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('uzb','Uzbek');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('vai','Vai');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ven','Venda');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('vie','Vietnamese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('vol','Volapük');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('vot','Votic');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('wak','Wakashan languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('wln','Walloon');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('war','Waray');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('was','Washo');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('wel','Welsh');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('cym','Welsh');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('fry','Western Frisian');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('wal','Wolaitta');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('wol','Wolof');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('xho','Xhosa');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('sah','Yakut');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('yao','Yao');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('yap','Yapese');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('yid','Yiddish');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('yor','Yoruba');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('ypk','Yupik languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('znd','Zande languages');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zap','Zapotec');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zen','Zenaga');
insert into  pariopp.lingue (ID,DESCRIZIONE) values('zul','Zulu');
COMMIT;
